version: "3.0"
services:      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - /C/test-docker/volume/elasticsearch-7.14.0:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - test
                  
networks:
  test:
    external:
      name: test